version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django_qrcode
    ports:
      - 8000:8000
    image: app:qr
    container_name: qrcode_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'qrcode'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./data/mysql/db:/var/lib/mysql
