# Generated by Django 3.2.9 on 2022-07-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=11)),
                ('fname', models.CharField(max_length=75)),
                ('lname', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=11)),
                ('website', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=255)),
                ('confirm', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('date', models.DateField(auto_now=True)),
                ('pdf', models.CharField(max_length=75)),
            ],
        ),
    ]
